const mongoose = require('mongoose');

// Schema cho Word Family (gia đình từ)
const wordFamilySchema = new mongoose.Schema({
    word: {
        type: String,
        required: true,
        trim: true
    },
    type: {
        type: String,
        enum: ['noun', 'verb', 'adjective', 'adverb', 'other'],
        required: true
    },
    meaning: {
        type: String,
        trim: true
    }
}, { _id: false });

// Schema chính cho Vocabulary
const vocabularySchema = new mongoose.Schema({
    word: {
        type: String,
        required: true,
        trim: true,
        lowercase: true
    },
    displayWord: {
        type: String,
        required: false, // Optional - will be auto-generated by pre-save hook if not provided
        trim: true
    },
    type: {
        type: String,
        required: true,
        enum: ['noun', 'verb', 'adjective', 'adverb', 'phrase', 'idiom'],
        index: true
    },
    meaning: {
        type: String,
        required: true,
        trim: true,
        maxlength: 2000
    },
    pronunciation: {
        ipa: {
            type: String,
            trim: true
        },
        audioUrl: {
            type: String,
            trim: true
        }
    },
    // Từ đồng nghĩa
    synonyms: [{
        type: String,
        trim: true
    }],
    // Từ trái nghĩa  
    antonyms: [{
        type: String,
        trim: true
    }],
    // Gia đình từ (Word Family)
    wordFamily: [wordFamilySchema],
    // Câu ví dụ
    examples: [{
        sentence: {
            type: String,
            trim: true,
            maxlength: 500
        },
        translation: {
            type: String,
            trim: true,
            maxlength: 500
        }
    }],
    // Cấp độ
    level: {
        type: String,
        enum: ['beginner', 'intermediate', 'advanced'],
        default: 'beginner',
        index: true
    },
    // Chủ đề liên quan
    topics: [{
        type: String,
        trim: true,
        maxlength: 100
    }],
    // Hình ảnh minh họa
    imageUrl: {
        type: String,
        trim: true
    },
    // Ghi chú cho giáo viên
    teacherNotes: {
        type: String,
        trim: true,
        maxlength: 1000
    },
    // Liên kết với các hội thoại
    relatedConversations: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Conversation'
    }],
    // Người tạo
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    // Người sửa cuối
    lastModifiedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    // Trạng thái
    isActive: {
        type: Boolean,
        default: true
    },
    // Số lần sử dụng
    usageCount: {
        type: Number,
        default: 0,
        min: 0
    },
    // Độ khó (1-5)
    difficulty: {
        type: Number,
        min: 1,
        max: 5,
        default: 1
    }
}, {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
});

// Indexes cho performance
vocabularySchema.index({ word: 1 }, { unique: true });
vocabularySchema.index({ type: 1, level: 1 });
vocabularySchema.index({ topics: 1 });
vocabularySchema.index({ isActive: 1 });
vocabularySchema.index({ createdBy: 1 });
vocabularySchema.index({ createdAt: -1 });
vocabularySchema.index({ word: 'text', meaning: 'text' }); // Text search

// Virtual để lấy thông tin người tạo
vocabularySchema.virtual('creator', {
    ref: 'User',
    localField: 'createdBy',
    foreignField: '_id',
    justOne: true
});

// Virtual để lấy thông tin người sửa cuối
vocabularySchema.virtual('lastModifier', {
    ref: 'User',
    localField: 'lastModifiedBy',
    foreignField: '_id',
    justOne: true
});

// Pre-save middleware để tạo displayWord từ word
vocabularySchema.pre('save', function (next) {
    if (this.isModified('word') && !this.displayWord) {
        // Capitalize first letter
        this.displayWord = this.word.charAt(0).toUpperCase() + this.word.slice(1);
    }
    next();
});

// Static method để tìm kiếm từ vựng
vocabularySchema.statics.findByFilters = function (filters = {}) {
    const query = {};

    if (filters.type) {
        query.type = filters.type;
    }

    if (filters.level) {
        query.level = filters.level;
    }

    if (filters.isActive !== undefined) {
        query.isActive = filters.isActive;
    }

    if (filters.topics && filters.topics.length > 0) {
        query.topics = { $in: filters.topics };
    }

    if (filters.search) {
        query.$or = [
            { word: new RegExp(filters.search, 'i') },
            { displayWord: new RegExp(filters.search, 'i') },
            { meaning: new RegExp(filters.search, 'i') }
        ];
    }

    return this.find(query);
};

// Instance method để cập nhật usage count
vocabularySchema.methods.incrementUsage = function () {
    this.usageCount += 1;
    return this.save();
};

// Instance method để kiểm tra quyền chỉnh sửa
vocabularySchema.methods.canEdit = function (userId, userRoles) {
    return userRoles.includes('admin') ||
        (userRoles.includes('teacher') && this.createdBy.toString() === userId.toString());
};

module.exports = mongoose.model('Vocabulary', vocabularySchema);
